"use client";
import {FormEvent,useCallback,useEffect,useRef,useState} from "react";
import type {Category,Product} from "@/lib/database.types";
declare global{interface Window{Telegram?:{WebApp?:{initData:string;ready():void;expand():void}}}}
type SessionResponse={error?:string;admin:{display_name:string|null};telegram:{first_name:string}};type DataResponse<T>={data?:T;error?:string};type ProductDraft={name:string;slug:string;description:string;price:string;category_id:string;is_published:boolean;is_available:boolean};
const emptyDraft:ProductDraft={name:"",slug:"",description:"",price:"",category_id:"",is_published:true,is_available:true};const slugify=(v:string)=>v.toLowerCase().trim().replace(/ё/g,"е").replace(/[^a-zа-я0-9]+/gi,"-").replace(/^-|-$/g,"");
export default function AdminShell(){const initData=useRef("");const [status,setStatus]=useState("Проверяем доступ…");const [products,setProducts]=useState<Product[]>([]);const [categories,setCategories]=useState<Category[]>([]);const [draft,setDraft]=useState<ProductDraft>(emptyDraft);const [busy,setBusy]=useState(false);const [ready,setReady]=useState(false);
const request=useCallback(async<T,>(path:string,options:RequestInit={}):Promise<T>=>{const response=await fetch(path,{...options,headers:{"content-type":"application/json","x-telegram-init-data":initData.current,...options.headers}});if(response.status===204)return undefined as T;const json=await response.json() as DataResponse<T>;if(!response.ok)throw new Error(json.error??"Ошибка запроса");return json.data as T},[]);const refresh=useCallback(async()=>{const [p,c]=await Promise.all([request<Product[]>("/api/admin/products"),request<Category[]>("/api/admin/categories")]);setProducts(p);setCategories(c.sort((a,b)=>a.sort_order-b.sort_order))},[request]);
useEffect(()=>{const app=window.Telegram?.WebApp;app?.ready();app?.expand();if(!app?.initData){queueMicrotask(()=>setStatus("Откройте эту страницу через Telegram Mini App."));return}initData.current=app.initData;request<SessionResponse>("/api/admin/session",{method:"POST"}).then(session=>{setStatus(`Здравствуйте, ${session.admin.display_name||session.telegram.first_name}`);setReady(true);return refresh()}).catch((error:unknown)=>setStatus(error instanceof Error?error.message:"Ошибка доступа"))},[refresh,request]);
async function createProduct(event:FormEvent){event.preventDefault();const price=Number(draft.price.replace(",","."));if(!draft.name.trim()||!draft.slug.trim()||!Number.isFinite(price)||price<0){setStatus("Заполните название, slug и корректную цену");return}setBusy(true);try{await request<Product>("/api/admin/products",{method:"POST",body:JSON.stringify({name:draft.name.trim(),slug:draft.slug.trim(),description:draft.description.trim(),price_minor:Math.round(price*100),currency:"RUB",category_id:draft.category_id||null,is_published:draft.is_published,is_available:draft.is_available})});setDraft(emptyDraft);await refresh();setStatus("Товар добавлен")}catch(error){setStatus(error instanceof Error?error.message:"Не удалось добавить товар")}finally{setBusy(false)}}
async function patchProduct(id:string,changes:Partial<Product>){setBusy(true);try{await request<Product>(`/api/admin/products/${id}`,{method:"PATCH",body:JSON.stringify(changes)});await refresh();setStatus("Изменения сохранены")}catch(error){setStatus(error instanceof Error?error.message:"Ошибка сохранения")}finally{setBusy(false)}}
async function editProduct(product:Product){const name=window.prompt("Название товара",product.name);if(name===null)return;const price=window.prompt("Цена в рублях",String(product.price_minor/100));if(price===null)return;const parsed=Number(price.replace(",","."));if(!name.trim()||!Number.isFinite(parsed)||parsed<0){setStatus("Проверьте название и цену");return}await patchProduct(product.id,{name:name.trim(),price_minor:Math.round(parsed*100)})}
async function removeProduct(product:Product){if(!window.confirm(`Удалить «${product.name}»?`))return;setBusy(true);try{await request<never>(`/api/admin/products/${product.id}`,{method:"DELETE"});await refresh();setStatus("Товар удалён")}catch(error){setStatus(error instanceof Error?error.message:"Ошибка удаления")}finally{setBusy(false)}}
return <main className="admin"><div className="adminbar"><div className="wrap brand">LAFLEUR · ADMIN</div></div><div className="wrap"><section className="panel"><h1>Управление магазином</h1><p className="status">{status}</p></section>{ready&&<><section className="panel"><div className="panel-title"><h2>Новый товар</h2></div><form className="admin-form" onSubmit={createProduct}><label>Название<input value={draft.name} onChange={e=>setDraft(v=>({...v,name:e.target.value,slug:v.slug||slugify(e.target.value)}))} placeholder="Букет Лаванда" required/></label><label>Slug<input value={draft.slug} onChange={e=>setDraft(v=>({...v,slug:slugify(e.target.value)}))} placeholder="buket-lavanda" required/></label><label>Цена, ₽<input inputMode="decimal" value={draft.price} onChange={e=>setDraft(v=>({...v,price:e.target.value}))} placeholder="4990" required/></label><label>Категория<select value={draft.category_id} onChange={e=>setDraft(v=>({...v,category_id:e.target.value}))}><option value="">Без категории</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="full">Описание<textarea value={draft.description} onChange={e=>setDraft(v=>({...v,description:e.target.value}))} placeholder="Состав и настроение букета" rows={3}/></label><label className="check"><input type="checkbox" checked={draft.is_published} onChange={e=>setDraft(v=>({...v,is_published:e.target.checked}))}/> Опубликовать</label><label className="check"><input type="checkbox" checked={draft.is_available} onChange={e=>setDraft(v=>({...v,is_available:e.target.checked}))}/> В наличии</label><button className="button full" disabled={busy}>{busy?"Сохраняем…":"Добавить товар"}</button></form></section><section className="panel"><div className="panel-title"><h2>Товары</h2><span className="chip">{products.length}</span></div><div className="product-list">{products.map(product=><article className="admin-product" key={product.id}><div><strong>{product.name}</strong><div className="muted">{(product.price_minor/100).toLocaleString("ru-RU")} ₽ · {product.slug}</div></div><div className="admin-actions"><button disabled={busy} onClick={()=>void editProduct(product)}>Изменить</button><button disabled={busy} onClick={()=>void patchProduct(product.id,{is_published:!product.is_published})}>{product.is_published?"Скрыть":"Опубликовать"}</button><button disabled={busy} onClick={()=>void patchProduct(product.id,{is_available:!product.is_available})}>{product.is_available?"Нет в наличии":"В наличии"}</button><button className="danger" disabled={busy} onClick={()=>void removeProduct(product)}>Удалить</button></div></article>)}</div></section></>}</div></main>}
