"use client";
import { useEffect, useState } from "react";
import type { Product } from "@/lib/database.types";

declare global{interface Window{Telegram?:{WebApp?:{initData:string;ready():void;expand():void}}}}
type SessionResponse={error?:string;admin:{display_name:string|null};telegram:{first_name:string}};
type ProductsResponse={data?:Product[]};

export default function AdminShell(){const [status,setStatus]=useState("Проверяем доступ…");const [products,setProducts]=useState<Product[]>([]);useEffect(()=>{const webApp=window.Telegram?.WebApp;webApp?.ready();webApp?.expand();const initData=webApp?.initData;if(!initData){queueMicrotask(()=>setStatus("Откройте эту страницу через Telegram Mini App."));return}const headers={"x-telegram-init-data":initData};fetch("/api/admin/session",{method:"POST",headers}).then(async r=>{const j=await r.json() as SessionResponse;if(!r.ok)throw new Error(j.error??"Ошибка доступа");setStatus(`Здравствуйте, ${j.admin.display_name||j.telegram.first_name}`);return fetch("/api/admin/products",{headers})}).then(async r=>await r.json() as ProductsResponse).then(j=>setProducts(j.data??[])).catch((e:unknown)=>setStatus(e instanceof Error?e.message:"Ошибка доступа"))},[]);return <main className="admin"><div className="adminbar"><div className="wrap brand">LAFLEUR · ADMIN</div></div><div className="wrap"><section className="panel"><h1>Управление магазином</h1><p className="status">{status}</p><p className="muted">CRUD API доступен для товаров, категорий, заказов, промокодов и изображений.</p></section><section className="panel"><h2>Товары</h2><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Название</th><th>Цена</th><th>Опубликован</th><th>В наличии</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td>{p.name}</td><td>{(p.price_minor/100).toLocaleString("ru-RU")} ₽</td><td>{p.is_published?"Да":"Нет"}</td><td>{p.is_available?"Да":"Нет"}</td></tr>)}</tbody></table></div></section></div></main>}
